export type Language = 'en' | 'zh-CN'

const english = {
  'recovery.count': '{count} recoverable drafts',
  'recovery.label': 'Recoverable drafts',
  'recovery.one': '{count} draft',
  'recovery.many': '{count} drafts',
  'recovery.restore': 'Restore draft: {title}',
  'recovery.path': 'path {path}',
  'recovery.file': 'File draft',
  'recovery.missing': 'Original file unavailable',
  'recovery.untitled': 'Untitled',
  'recovery.characters': '{count} characters',
  'menu.file': 'File',
  'menu.fileActions': 'File actions',
  'menu.insert': 'Insert',
  'menu.view': 'View',
  'menu.language': 'Language',
  'menu.switchLanguage': 'Switch to Simplified Chinese',
  'menu.new': 'New',
  'menu.open': 'Open',
  'menu.save': 'Save',
  'menu.openFolder': 'Open Folder',
  'menu.saveAs': 'Save As…',
  'menu.exportHtml': 'Export HTML…',
  'menu.exportPdf': 'Export PDF…',
  'menu.pdfSettings': 'PDF export settings',
  'menu.paperSize': 'Paper size',
  'menu.margin': 'Margins',
  'menu.marginNarrow': 'Narrow · 10 mm',
  'menu.marginNormal': 'Normal · 18 mm',
  'menu.marginWide': 'Wide · 25 mm',
  'menu.pageBreakH1': 'Start each H1 on a new page',
  'menu.recentFiles': 'Recent files',
  'status.editing': 'Editing',
  'status.saving': 'Saving…',
  'status.saved': 'Saved',
  'status.error': 'Save failed',
  'status.conflict': 'Disk conflict',
  'tabs.label': 'Document tabs',
  'tabs.untitled': 'Untitled',
  'tabs.close': 'Close {name}',
  'tabs.closeTitle': 'Close tab (⌘/Ctrl+W)',
  'tabs.new': 'New document tab',
  'tabs.reloadDisk': 'Reload from disk',
  'tabs.saveCopy': 'Save a copy',
  'tabs.retry': 'Retry',
  'toolbar.sidebar': 'Sidebar',
  'toolbar.format': 'Format',
  'toolbar.headingLevel': 'Heading level',
  'toolbar.body': 'Body',
  'toolbar.currentH6': 'H6 (current)',
  'toolbar.bold': 'Bold',
  'toolbar.italic': 'Italic',
  'toolbar.link': 'Link',
  'insert.inlineCode': 'Inline code',
  'insert.quote': 'Quote',
  'insert.codeBlock': 'Code block',
  'insert.listFormat': 'List format',
  'insert.chooseList': 'Choose list type',
  'insert.unordered': 'Bulleted list',
  'insert.ordered': 'Numbered list',
  'insert.task': 'Task list',
  'insert.table': 'Table',
  'insert.editTable': 'Edit current table',
  'insert.tableCannotEdit': 'This table has extra cells and cannot be edited safely.',
  'insert.insertRow': 'Insert row below',
  'insert.deleteRow': 'Delete current row',
  'insert.insertColumn': 'Insert column right',
  'insert.deleteColumn': 'Delete current column',
  'insert.columnAlign': 'Current column alignment',
  'insert.setColumnAlign': 'Set current column alignment',
  'insert.alignDefault': 'Default',
  'insert.alignLeft': 'Left',
  'insert.alignCenter': 'Center',
  'insert.alignRight': 'Right',
  'insert.newTable': 'Insert new table',
  'insert.columns': 'Columns',
  'insert.bodyRows': 'Body rows',
  'insert.insertTable': 'Insert table',
  'insert.cancel': 'Cancel',
  'insert.columnHeader': 'Column {index}',
  'view.findReplace': 'Find and replace',
  'view.focusMode': 'Focus mode',
  'view.typewriterMode': 'Typewriter mode',
  'view.theme': 'Appearance',
  'view.themeSystem': 'Follow system',
  'view.themeLight': 'Light',
  'view.themeDark': 'Dark',
  'view.previewOn': 'Preview on',
  'view.previewOff': 'Preview off',
  'view.layout': 'Document layout',
  'view.editorOnly': 'Edit',
  'view.splitView': 'Split',
  'view.splitDescription': 'Show editor and preview side by side',
  'view.previewOnly': 'Preview',
  'sidebar.files': 'Files',
  'sidebar.search': 'Search',
  'sidebar.outline': 'Outline',
  'sidebar.workspaceSearch': 'Search files',
  'sidebar.collapse': 'Collapse {title}',
  'sidebar.filterHeadings': 'Filter headings',
  'sidebar.filterPlaceholder': 'Filter headings',
  'sidebar.documentHeadings': 'Headings in this document',
  'sidebar.expandHeading': 'Expand {title}',
  'sidebar.collapseHeading': 'Collapse {title}',
  'sidebar.emptyHeading': 'Untitled heading',
  'sidebar.headingLine': 'H{level} · Line {line}',
  'sidebar.noMatchingHeadings': 'No matching headings',
  'sidebar.addHeading': 'Add a heading to navigate here',
  'sidebar.switchFolder': 'Switch folder',
  'sidebar.chooseFolder': 'Choose folder',
  'sidebar.closeFolder': 'Close folder',
  'sidebar.chooseFolderToSearch': 'Choose a folder to search',
  'sidebar.searchMarkdown': 'Search Markdown in this folder',
  'sidebar.searchPlaceholder': 'Search Markdown content',
  'sidebar.searching': 'Searching…',
  'sidebar.searchButton': 'Search',
  'sidebar.searchResults': '{count} results',
  'sidebar.firstHundred': 'Showing first 100',
  'sidebar.skipped': '{count} skipped',
  'sidebar.loading': 'Loading…',
  'sidebar.noMarkdown': 'No Markdown files',
  'pane.editor': 'Editor',
  'pane.preview': 'Preview',
  'pane.updating': 'Updating…',
  'pane.previewFailed': 'Preview failed: {error}',
  'pane.localDraft': 'Local draft · no file assigned',
  'pane.words': '{count} words',
  'pane.cursor': 'Line {line}, Column {column}',
  'pane.copy': 'Copy',
  'pane.copied': 'Copied',
  'pane.copyCode': 'Copy code block',
  'pane.imageSaveFirst': 'Save the file to preview local images',
  'pane.imageUnreadable': 'Unable to read image: {name}',
  'pane.remoteImageBlocked': 'Remote image not loaded: {name}',
  'pane.imagePathBlocked': 'Image path blocked: {name}',
  'pane.diagramFailed': 'Diagram could not render: {error}',
  'pane.diagramEmpty': 'Diagram is empty or exceeds 50,000 characters',
  'pane.diagramInvalid': 'Invalid syntax',
  'export.saveMarkdownFirst': 'Save the document as Markdown before exporting local images',
  'export.imageReadFailed': 'Could not read image {name}: {error}',
  'export.extensionRequired': 'Use the {extension} extension to save the export',
  'common.image': 'Image',
  'common.text': 'Text',
  'notice.saveAsCollision': 'The target file is already open in another tab. Choose another location; your content is still here.',
  'notice.saveAsFailed': 'Save As failed: {error}',
  'notice.exported': 'Exported to {path}',
  'notice.exportFailed': 'Export {format} failed: {error}',
  'notice.imagesLimit': 'Import up to 20 images at once; each must be 10 MB or less, and the total 50 MB or less.',
  'notice.imageUnsupported': 'Only PNG, JPEG, GIF, WebP and AVIF images are supported',
  'notice.importFailed': 'Image import failed: {error}',
  'notice.mixedLineError': 'This file has mixed line endings. Confirm conversion to LF or save a copy.',
  'notice.mixedLineConfirm': 'This file has mixed line endings. Saving will convert them to LF. Continue?',
  'notice.mixedLineNotice': 'This file has mixed line endings. Confirm conversion to LF before saving or save a copy.',
  'notice.staleSearch': 'The search result has changed. Search again.',
  'notice.closedBackup': 'Tab closed. Recover unsaved content from drafts.',
  'notice.closeFailed': 'Could not safely close the tab; content remains: {error}',
  'notice.draftDiskChanged': 'The file changed on disk after this draft was created. Reload it or save the draft as a copy.',
  'notice.draftSourceMissing': 'The original file is unavailable. The draft opened as an untitled document.',
  'notice.draftAlreadyOpen': 'The original file is open in another tab. The draft opened as an untitled copy.',
  'notice.restoreFailed': 'Draft recovery failed: {error}',
  'notice.draftBackupFailed': '{name} draft backup failed: {error}',
  'notice.diagramPreviewFailed': 'Diagram preview failed: {error}',
  'notice.externalChanged': 'The file changed on disk. Reload it or save a copy.',
  'notice.closeBusy': 'Wait for the current file operation before closing the window',
  'notice.beforeCloseBackupFailed': 'Could not back up drafts before closing: {error}',
  'notice.copyFailed': 'Copy failed: {error}',
  'notice.unknownError': 'Operation failed: {error}',
  'search.find': 'Find in document',
  'search.previous': 'Previous match',
  'search.next': 'Next match',
  'search.close': 'Close search',
  'search.matchCase': 'Match case',
  'search.regexp': 'Regular expression',
  'search.wholeWord': 'Whole word',
  'search.showReplace': 'Show replace',
  'search.hideReplace': 'Hide replace',
  'search.replaceInput': 'Replace with',
  'search.replace': 'Replace',
  'search.replaceAll': 'Replace all',
  'search.invalidRegex': 'Invalid regular expression'
} as const

const chinese: Record<keyof typeof english, string> = {
  'recovery.count': '{count} 份可恢复草稿',
  'recovery.label': '可恢复草稿',
  'recovery.one': '{count} 份',
  'recovery.many': '{count} 份',
  'recovery.restore': '恢复草稿：{title}',
  'recovery.path': '路径 {path}',
  'recovery.file': '文件草稿',
  'recovery.missing': '原文件不可用',
  'recovery.untitled': '未命名',
  'recovery.characters': '{count} 字符',
  'menu.file': '文件',
  'menu.fileActions': '文件操作',
  'menu.insert': '插入',
  'menu.view': '视图',
  'menu.language': '语言',
  'menu.switchLanguage': '切换到 English',
  'menu.new': '新建',
  'menu.open': '打开',
  'menu.save': '保存',
  'menu.openFolder': '打开文件夹',
  'menu.saveAs': '另存为…',
  'menu.exportHtml': '导出 HTML…',
  'menu.exportPdf': '导出 PDF…',
  'menu.pdfSettings': 'PDF 导出设置',
  'menu.paperSize': '纸张尺寸',
  'menu.margin': '页边距',
  'menu.marginNarrow': '窄 · 10 mm',
  'menu.marginNormal': '标准 · 18 mm',
  'menu.marginWide': '宽 · 25 mm',
  'menu.pageBreakH1': '一级标题从新页开始',
  'menu.recentFiles': '最近文件',
  'status.editing': '编辑中',
  'status.saving': '正在保存',
  'status.saved': '已保存',
  'status.error': '保存失败',
  'status.conflict': '磁盘冲突',
  'tabs.label': '文档标签',
  'tabs.untitled': '未命名文档',
  'tabs.close': '关闭 {name}',
  'tabs.closeTitle': '关闭标签 (⌘/Ctrl+W)',
  'tabs.new': '新建文档标签',
  'tabs.reloadDisk': '重新载入磁盘文件',
  'tabs.saveCopy': '将当前内容另存副本',
  'tabs.retry': '重试',
  'toolbar.sidebar': '侧栏',
  'toolbar.format': '格式',
  'toolbar.headingLevel': '标题级别',
  'toolbar.body': '正文',
  'toolbar.currentH6': 'H6（当前）',
  'toolbar.bold': '粗体',
  'toolbar.italic': '斜体',
  'toolbar.link': '链接',
  'insert.inlineCode': '行内代码',
  'insert.quote': '引用',
  'insert.codeBlock': '代码块',
  'insert.listFormat': '列表格式',
  'insert.chooseList': '选择列表类型',
  'insert.unordered': '无序列表',
  'insert.ordered': '有序列表',
  'insert.task': '任务列表',
  'insert.table': '表格',
  'insert.editTable': '编辑当前表格',
  'insert.tableCannotEdit': '此表格有额外单元格，无法安全编辑。',
  'insert.insertRow': '下方插入行',
  'insert.deleteRow': '删除当前行',
  'insert.insertColumn': '右侧插入列',
  'insert.deleteColumn': '删除当前列',
  'insert.columnAlign': '当前列对齐',
  'insert.setColumnAlign': '设置当前列对齐',
  'insert.alignDefault': '默认',
  'insert.alignLeft': '左对齐',
  'insert.alignCenter': '居中',
  'insert.alignRight': '右对齐',
  'insert.newTable': '插入新表格',
  'insert.columns': '列数',
  'insert.bodyRows': '正文行数',
  'insert.insertTable': '插入表格',
  'insert.cancel': '取消',
  'insert.columnHeader': '表头 {index}',
  'view.findReplace': '查找与替换',
  'view.focusMode': '专注模式',
  'view.typewriterMode': '打字机模式',
  'view.theme': '外观主题',
  'view.themeSystem': '跟随系统',
  'view.themeLight': '浅色',
  'view.themeDark': '深色',
  'view.previewOn': '预览开启',
  'view.previewOff': '预览关闭',
  'view.layout': '文档布局',
  'view.editorOnly': '编辑',
  'view.splitView': '双栏',
  'view.splitDescription': '同时显示编辑与预览',
  'view.previewOnly': '预览',
  'sidebar.files': '文件',
  'sidebar.search': '搜索',
  'sidebar.outline': '目录',
  'sidebar.workspaceSearch': '跨文件搜索',
  'sidebar.collapse': '收起{title}',
  'sidebar.filterHeadings': '筛选目录标题',
  'sidebar.filterPlaceholder': '筛选标题',
  'sidebar.documentHeadings': '当前文档标题',
  'sidebar.expandHeading': '展开 {title}',
  'sidebar.collapseHeading': '折叠 {title}',
  'sidebar.emptyHeading': '空标题',
  'sidebar.headingLine': 'H{level} · 第 {line} 行',
  'sidebar.noMatchingHeadings': '没有匹配的标题',
  'sidebar.addHeading': '添加标题后在这里导航',
  'sidebar.switchFolder': '切换文件夹',
  'sidebar.chooseFolder': '选择文件夹',
  'sidebar.closeFolder': '关闭文件夹',
  'sidebar.chooseFolderToSearch': '选择文件夹后搜索',
  'sidebar.searchMarkdown': '搜索文件夹内的 Markdown',
  'sidebar.searchPlaceholder': '搜索 Markdown 内容',
  'sidebar.searching': '搜索中…',
  'sidebar.searchButton': '搜索',
  'sidebar.searchResults': '{count} 条结果',
  'sidebar.firstHundred': '仅显示前 100 条',
  'sidebar.skipped': '跳过 {count} 项',
  'sidebar.loading': '读取中…',
  'sidebar.noMarkdown': '没有 Markdown 文件',
  'pane.editor': '编辑',
  'pane.preview': '预览',
  'pane.updating': '更新中…',
  'pane.previewFailed': '预览失败：{error}',
  'pane.localDraft': '本地草稿 · 尚未指定文件',
  'pane.words': '{count} 字',
  'pane.cursor': '第 {line} 行，第 {column} 列',
  'pane.copy': '复制',
  'pane.copied': '已复制',
  'pane.copyCode': '复制代码块',
  'pane.imageSaveFirst': '保存文件后可预览本地图片',
  'pane.imageUnreadable': '图片无法读取：{name}',
  'pane.remoteImageBlocked': '远程图片未加载：{name}',
  'pane.imagePathBlocked': '图片路径受限：{name}',
  'pane.diagramFailed': '图表无法渲染：{error}',
  'pane.diagramEmpty': '图表内容为空或超过 50,000 字符',
  'pane.diagramInvalid': '语法无效',
  'export.saveMarkdownFirst': '包含本地图片的文档需要先保存为 Markdown 文件',
  'export.imageReadFailed': '无法读取图片「{name}」：{error}',
  'export.extensionRequired': '请使用 {extension} 扩展名保存导出文件',
  'common.image': '图片',
  'common.text': '文本',
  'notice.saveAsCollision': '目标文件已在其他标签打开，请选择其他位置。当前内容已保留。',
  'notice.saveAsFailed': '另存为失败：{error}',
  'notice.exported': '已导出到 {path}',
  'notice.exportFailed': '导出 {format} 失败：{error}',
  'notice.imagesLimit': '一次最多导入 20 张图片；单张不超过 10 MB，总量不超过 50 MB。',
  'notice.imageUnsupported': '仅支持 PNG、JPEG、GIF、WebP 和 AVIF 图片',
  'notice.importFailed': '导入图片失败：{error}',
  'notice.mixedLineError': '文件包含混合换行，请手动确认转换为 LF 或另存副本',
  'notice.mixedLineConfirm': '文件包含混合换行。保存将统一转换为 LF。继续吗？',
  'notice.mixedLineNotice': '此文件包含混合换行。写回前需要确认统一为 LF，或另存副本。',
  'notice.staleSearch': '搜索结果对应的内容已改变，请重新搜索。',
  'notice.closedBackup': '已关闭标签，未保存内容可从恢复草稿找回。',
  'notice.closeFailed': '无法安全关闭标签，内容仍保留：{error}',
  'notice.draftDiskChanged': '草稿建立后磁盘文件已改变。请重新载入或将草稿另存副本。',
  'notice.draftSourceMissing': '原文件不可用，草稿已作为未命名文档打开。',
  'notice.draftAlreadyOpen': '原文档已在其他标签打开，恢复草稿已作为未命名副本打开。',
  'notice.restoreFailed': '恢复草稿失败：{error}',
  'notice.draftBackupFailed': '{name} 草稿备份失败：{error}',
  'notice.diagramPreviewFailed': '图表预览失败：{error}',
  'notice.externalChanged': '磁盘文件已改变。重新载入或将当前内容另存副本。',
  'notice.closeBusy': '请等待当前文件操作完成后再关闭窗口',
  'notice.beforeCloseBackupFailed': '关闭前无法备份草稿：{error}',
  'notice.copyFailed': '复制失败：{error}',
  'notice.unknownError': '操作失败：{error}',
  'search.find': '在文档中查找',
  'search.previous': '上一处',
  'search.next': '下一处',
  'search.close': '关闭搜索',
  'search.matchCase': '区分大小写',
  'search.regexp': '正则表达式',
  'search.wholeWord': '整词匹配',
  'search.showReplace': '显示替换',
  'search.hideReplace': '收起替换',
  'search.replaceInput': '替换为',
  'search.replace': '替换',
  'search.replaceAll': '全部替换',
  'search.invalidRegex': '正则表达式无效'
}

export const messages: Record<Language, Record<keyof typeof english, string>> = {
  en: english,
  'zh-CN': chinese
}

export type MessageKey = keyof typeof english

export function parseLanguage(value: string | null): Language {
  return value === 'zh-CN' ? 'zh-CN' : 'en'
}

export function text(language: Language, key: MessageKey, values: Record<string, string | number> = {}): string {
  return messages[language][key].replace(/\{([a-zA-Z]+)\}/g, (_, name: string) => String(values[name] ?? '{' + name + '}'))
}
